# Generated by Django 2.1.15 on 2023-12-08 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='priority',
            field=models.CharField(default='Medium', max_length=50),
        ),
        migrations.AlterField(
            model_name='bug',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bug',
            name='project',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bug',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_bugs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bug',
            name='status',
            field=models.CharField(default='Open', max_length=100),
        ),
        migrations.AlterField(
            model_name='bug',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
