version: 0.2
 
phases:
  pre_build:
    runtime-versions:
      python: 3.11
    commands:
      # Install dependencies needed
      - echo "Pre-Build Phase - Starting....."
      - pip install --upgrade pip
      - echo "Dependencies installation from requirements.txt file"
      - pip install -r requirements.txt
 
  build:
    commands:
      - echo "Build Phase - Starting"
      - echo Build started on `date`
      - python manage.py migrate
     # - echo "Running Pylint"
      #- cd Dashboard
     # - pylint ./*
 
  post_build:
    commands:
      - echo "Post-Build Phase - Starting"
      - echo Build completed on `date`
 
artifacts:
  files:
    - '**/*'